# Generated by Django 3.1.4 on 2020-12-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201118_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='date_of_joined',
        ),
    ]
